/**
 * STA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParentVM { 
    id?: number;
    userId?: string | null;
    userName?: string | null;
    email?: string | null;
}

